language: node_js
node_js:
- node
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token: "$FIREBASE_TOKEN"
  project: "$FIREBASE_PROJECT_ID"
  on:
    branch: master
cache:
  yarn: true
  directories:
  - node_modules
