language: node_js
node_js:
- node
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "$FIREBASE_PROJECT_ID"
cache:
  yarn: true
  directories:
  - node_modules
