language: node_js

node_js:
  - 7

script:
  - yarn build

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "$FIREBASE_PROJECT_ID"

cache:
  yarn: true
  directories:
    - node_modules
