export const ADD_CATEGORY_DATA_REQUEST = 'ADD_CATEGORY_DATA_REQUEST';
export const ADD_CATEGORY_DATA_SUCCESS = 'ADD_CATEGORY_DATA_SUCCESS';
export const ADD_CATEGORY_DATA_FAILURE = 'ADD_CATEGORY_DATA_FAILURE';

export const ADD_CATEGORY_SAVE_REQUEST = 'ADD_CATEGORY_SAVE_REQUEST';
export const ADD_CATEGORY_SAVE_SUCCESS = 'ADD_CATEGORY_SAVE_SUCCESS';
export const ADD_CATEGORY_SAVE_FAILURE = 'ADD_CATEGORY_SAVE_FAILURE';
