export const ADD_VIOLATION_DATA_REQUEST = 'ADD_VIOLATION_DATA_REQUEST';
export const ADD_VIOLATION_DATA_SUCCESS = 'ADD_VIOLATION_DATA_SUCCESS';
export const ADD_VIOLATION_DATA_FAILURE = 'ADD_VIOLATION_DATA_FAILURE';

export const ADD_VIOLATION_SAVE_REQUEST = 'ADD_VIOLATION_SAVE_REQUEST';
export const ADD_VIOLATION_SAVE_SUCCESS = 'ADD_VIOLATION_SAVE_SUCCESS';
export const ADD_VIOLATION_SAVE_FAILURE = 'ADD_VIOLATION_SAVE_FAILURE';
