export const COMPANIES_REQUEST = 'COMPANIES_REQUEST';
export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';

export const LOYALTY_CHANGED = 'LOYALTY_CHANGED';
export const CATEGORY_CHANGED = 'CATEGORY_CHANGED';
export const VIOLATION_CHANGED = 'VIOLATION_CHANGED';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
