export const CREATE_COMPANY_DATA_REQUEST = 'CREATE_COMPANY_DATA_REQUEST';
export const CREATE_COMPANY_DATA_SUCCESS = 'CREATE_COMPANY_DATA_SUCCESS';
export const CREATE_COMPANY_DATA_FAILURE = 'CREATE_COMPANY_DATA_FAILURE';

export const CREATE_COMPANY_SAVE_REQUEST = 'CREATE_COMPANY_SAVE_REQUEST';
export const CREATE_COMPANY_SAVE_SUCCESS = 'CREATE_COMPANY_SAVE_SUCCESS';
export const CREATE_COMPANY_SAVE_FAILURE = 'CREATE_COMPANY_SAVE_FAILURE';
