export const CREATE_COMPANY_DATA_REQUEST = 'CREATE_COMPANY_DATA_REQUEST';
export const CREATE_COMPANY_DATA_SUCCESS = 'CREATE_COMPANY_DATA_SUCCESS';
export const CREATE_COMPANY_DATA_FAILURE = 'CREATE_COMPANY_DATA_FAILURE';
