export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';

export const PLEASE_SIGNUP_DIALOG = 'PLEASE_SIGNUP_DIALOG';
export const SUCCESS_DIALOG = 'SUCCESS_DIALOG';

export const LOGIN_DIALOG = 'LOGIN_DIALOG';
export const SIGNUP_DIALOG = 'SIGNUP_DIALOG';
export const CREATE_COMPANY_DIALOG = 'CREATE_COMPANY_DIALOG';
export const ADD_VIOLATION_DIALOG = 'ADD_VIOLATION_DIALOG';
