export const LAST_COMMENTS_REQUEST = 'LAST_COMMENTS_REQUEST';
export const LAST_COMMENTS_SUCCESS = 'LAST_COMMENTS_SUCCESS';

export const NEW_COMPANIES_REQUEST = 'NEW_COMPANIES_REQUEST';
export const NEW_COMPANIES_SUCCESS = 'NEW_COMPANIES_SUCCESS';
