export const COMPANIES_REQUEST = 'COMPANIES_REQUEST';
export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';

export const LOYALTY_CHANGED = 'LOYALTY_CHANGED';
export const CATEGORY_CHANGED = 'CATEGORY_CHANGED';
export const ADD_VIOLATION_FILTER = 'ADD_VIOLATION_FILTER';
export const REMOVE_VIOLATION_FILTER = 'REMOVE_VIOLATION_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
