export const API_ROOT = 'http://localhost:5001'; //todo: config

export const GENERIC_REQUEST_ERROR = 'GENERIC_REQUEST_ERROR';
export const APP_READY = 'APP_READY';
export const PRELOAD_LOCATION_CHANGE_START = 'PRELOAD_LOCATION_CHANGE_START';
export const PRELOAD_LOCATION_CHANGE_END = 'PRELOAD_LOCATION_CHANGE_END';
