export const PRELOAD_INITIAL_DATA_REQUEST = 'PRELOAD_INITIAL_DATA_REQUEST';
export const PRELOAD_INITIAL_DATA_SUCCESS = 'PRELOAD_INITIAL_DATA_SUCCESS';

export const PRELOAD_LOCATION_CHANGED = 'PRELOAD_LOCATION_CHANGED';
